In [1]:
import numpy as np
a=np.array([1,4,9,16])
print(np.sqrt(a))

[1. 2. 3. 4.]


In [2]:
a=np.array([1,4,9,16,25])
print(a)
print(np.sqrt(a))
print(np.abs(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 1  4  9 16 25]
[1. 2. 3. 4. 5.]
[ 1  4  9 16 25]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
[ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641]


In [3]:
a=np.array([1,2,3])
b=a.copy()
b[1]=21
print(a)
print(b)

[1 2 3]
[ 1 21  3]


In [4]:
a=np.array([1,2,3])
b=a.view()
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [5]:
print(np.random.rand(5))

[0.63191327 0.92369363 0.78320793 0.28986657 0.49617327]


In [6]:
print(np.random.rand(5))

[0.12648391 0.32271485 0.24545825 0.12323313 0.58969043]


In [7]:
print(np.random.randint(1,100,(3,4)))

[[48 69 89 71]
 [ 9 36 87 61]
 [41 66 49 34]]


In [8]:
marks=np.array([99,90,88,84,72])
print(marks>90)

[ True False False False False]


In [9]:
marks=np.array([99,90,88,84,72])
print(marks[marks>90])

[99]


In [10]:
a=np.array([1,2,3])
print(a+10)

[11 12 13]


In [11]:
marks=np.array([99,90,88,84,72])
print("Average:",np.mean(marks))
print("Highest",np.max(marks))
print("Lowest",np.min(marks))

Average: 86.6
Highest 99
Lowest 72


In [12]:
salary=np.array([50000,48000,47000,45630,45678,98765,95763,34574,58695,95689,56500,48700,47880,45430,98778,95665,95236,32344,58345,95129,55000,49000,45000,45730,45678,92265,92163,34974,58595,85689,51000,48650,45000,45430,42678,98765,22763,34574,584565,97689,50000,48000,47000,45630,45678,98765,95763,34574,58695,95689,])
print(salary.size)
print("Mean:",np.mean(salary))
print("Median:",np.median(salary))
print("sum:",np.sum(salary))
print("maximum:",np.max(salary))
print("minimum:",np.min(salary))
new_salary=(salary*0.05)+salary
print(new_salary)
print(new_salary-salary)
print("maximum:",np.max(new_salary))
print("minimum:",np.min(new_salary))

50
Mean: 71776.06
Median: 49500.0
sum: 3588803
maximum: 584565
minimum: 22763
[ 52500.    50400.    49350.    47911.5   47961.9  103703.25 100551.15
  36302.7   61629.75 100473.45  59325.    51135.    50274.    47701.5
 103716.9  100448.25  99997.8   33961.2   61262.25  99885.45  57750.
  51450.    47250.    48016.5   47961.9   96878.25  96771.15  36722.7
  61524.75  89973.45  53550.    51082.5   47250.    47701.5   44811.9
 103703.25  23901.15  36302.7  613793.25 102573.45  52500.    50400.
  49350.    47911.5   47961.9  103703.25 100551.15  36302.7   61629.75
 100473.45]
[ 2500.    2400.    2350.    2281.5   2283.9   4938.25  4788.15  1728.7
  2934.75  4784.45  2825.    2435.    2394.    2271.5   4938.9   4783.25
  4761.8   1617.2   2917.25  4756.45  2750.    2450.    2250.    2286.5
  2283.9   4613.25  4608.15  1748.7   2929.75  4284.45  2550.    2432.5
  2250.    2271.5   2133.9   4938.25  1138.15  1728.7  29228.25  4884.45
  2500.    2400.    2350.    2281.5   2283.9   4938.25  47

In [13]:
import pandas as pd

In [14]:
marks=pd.Series([90,99,76,84])
print(marks)

0    90
1    99
2    76
3    84
dtype: int64


In [15]:
df=pd.read_csv("record.csv")

print(df)

           Name  English  Mathematics  Science  Social Studies  Computer
0  Aarav Sharma       85           92       78              88        95
1   Priya Verma       90           87       91              85        89
2   Rahul Singh       76           81       74              79        83
3  Ananya Gupta       95           93       96              90        98
4  Vikram Yadav       68           75       72              70        77
5   Neha Mishra       88           84       89              92        86
6  Aditya Kumar       79           86       80              75        82
7   Sneha Patel       92           89       94              91        93
8   Rohan Mehta       73           78       85              80        76
9   Kavya Joshi       86           91       88              87        90


In [16]:
marks=pd.Series([90,80],index=["A","B"])
print(marks)

A    90
B    80
dtype: int64


In [17]:
a=int(input("enter a number"))
b=int(input("enter another number"))
a,b=b,a
print(a,b)

enter a number 2
enter another number 3


3 2


In [18]:
import pandas as pd
df=pd.read_csv("data_100_rows_20_columns (1).csv")
print(df)

    Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0         48        45        78        24         8        85         1   
1         26        97        53        49        26         5        72   
2         63        48        77        51        40        95        61   
3          2        48        33        75        60        44        59   
4         84        54       100        67        37        34        73   
..       ...       ...       ...       ...       ...       ...       ...   
95        62        53        81        90        38        65        67   
96         5        94        23        33        19        60        24   
97        15        40        84        10         9        47        27   
98        25        73         9        16         4        33        55   
99        36        79        49        14        22        12        27   

    Column_8  Column_9  Column_10  Column_11  Column_12  Column_13  Column_14  \
0     

In [19]:
df.shape

(100, 20)

In [20]:
print(df.head())

   Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0        48        45        78        24         8        85         1   
1        26        97        53        49        26         5        72   
2        63        48        77        51        40        95        61   
3         2        48        33        75        60        44        59   
4        84        54       100        67        37        34        73   

   Column_8  Column_9  Column_10  Column_11  Column_12  Column_13  Column_14  \
0        58        54         50         64         49         95         75   
1        12        54         86         98         44         82         26   
2       100        29         20         83         19         34         46   
3        59        87         69         80         34         75         61   
4        23        16         51         69         35          7         41   

   Column_15  Column_16  Column_17  Column_18  Column_19  Column_20 

In [21]:
print(df.tail())

    Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
95        62        53        81        90        38        65        67   
96         5        94        23        33        19        60        24   
97        15        40        84        10         9        47        27   
98        25        73         9        16         4        33        55   
99        36        79        49        14        22        12        27   

    Column_8  Column_9  Column_10  Column_11  Column_12  Column_13  Column_14  \
95        62        54         54         32         17         91         63   
96        73        58          5         36         17         83         78   
97        15        96          7          3         37         96         64   
98         3        20         88         37         74         49         13   
99        57        92          6         51         88         28         32   

    Column_15  Column_16  Column_17  Column_18  Column_1

In [22]:
print(df.columns)

Index(['Column_1', 'Column_2', 'Column_3', 'Column_4', 'Column_5', 'Column_6',
       'Column_7', 'Column_8', 'Column_9', 'Column_10', 'Column_11',
       'Column_12', 'Column_13', 'Column_14', 'Column_15', 'Column_16',
       'Column_17', 'Column_18', 'Column_19', 'Column_20'],
      dtype='str')


In [23]:
print(df.index)

RangeIndex(start=0, stop=100, step=1)


In [24]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Column_1   100 non-null    int64
 1   Column_2   100 non-null    int64
 2   Column_3   100 non-null    int64
 3   Column_4   100 non-null    int64
 4   Column_5   100 non-null    int64
 5   Column_6   100 non-null    int64
 6   Column_7   100 non-null    int64
 7   Column_8   100 non-null    int64
 8   Column_9   100 non-null    int64
 9   Column_10  100 non-null    int64
 10  Column_11  100 non-null    int64
 11  Column_12  100 non-null    int64
 12  Column_13  100 non-null    int64
 13  Column_14  100 non-null    int64
 14  Column_15  100 non-null    int64
 15  Column_16  100 non-null    int64
 16  Column_17  100 non-null    int64
 17  Column_18  100 non-null    int64
 18  Column_19  100 non-null    int64
 19  Column_20  100 non-null    int64
dtypes: int64(20)
memory usage: 15.7 KB
None


In [25]:
print(df.describe())

         Column_1    Column_2    Column_3    Column_4    Column_5    Column_6  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean    47.450000   57.220000   51.450000   53.210000   50.760000   51.360000   
std     28.306895   28.869466   29.609026   27.805346   30.591845   30.519581   
min      2.000000    1.000000    1.000000    1.000000    3.000000    2.000000   
25%     24.000000   34.750000   23.000000   29.750000   25.000000   22.750000   
50%     44.000000   60.000000   49.500000   55.000000   46.000000   55.500000   
75%     74.000000   82.250000   78.250000   78.000000   81.250000   77.500000   
max     98.000000  100.000000  100.000000  100.000000   99.000000  100.000000   

         Column_7    Column_8    Column_9   Column_10   Column_11  Column_12  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.00000   
mean    55.220000   48.240000   46.160000   49.300000   48.810000   48.97000   
std     29.336288   28.261449 

In [26]:
df=pd.read_csv("employee_data.csv")

print(df)

   employee_id             name   department   salary
0          101      Alice Smith  Engineering  85000.0
1          102        Bob Jones    Marketing  62000.0
2          103    Charlie Brown      Finance      0.0
3          104     Diana Prince          NaN  75000.0
4          105      Evan Wright  Engineering  92000.0
5          106  Fiona Gallagher           HR  58000.0
6          107     George Clark    Marketing      NaN
7          108    Hannah Abbott      Finance      0.0
8          109      Ian Malcolm        Sales  81000.0
9          110    Julia Roberts           HR  67000.0


In [27]:
print(df["name"])

0        Alice Smith
1          Bob Jones
2      Charlie Brown
3       Diana Prince
4        Evan Wright
5    Fiona Gallagher
6       George Clark
7      Hannah Abbott
8        Ian Malcolm
9      Julia Roberts
Name: name, dtype: str


In [28]:
print(df[["name","employee_id"]])

              name  employee_id
0      Alice Smith          101
1        Bob Jones          102
2    Charlie Brown          103
3     Diana Prince          104
4      Evan Wright          105
5  Fiona Gallagher          106
6     George Clark          107
7    Hannah Abbott          108
8      Ian Malcolm          109
9    Julia Roberts          110


In [29]:
print(df[["name","salary"]])

              name   salary
0      Alice Smith  85000.0
1        Bob Jones  62000.0
2    Charlie Brown      0.0
3     Diana Prince  75000.0
4      Evan Wright  92000.0
5  Fiona Gallagher  58000.0
6     George Clark      NaN
7    Hannah Abbott      0.0
8      Ian Malcolm  81000.0
9    Julia Roberts  67000.0


In [30]:
print(df[["name","salary","department"]])

              name   salary   department
0      Alice Smith  85000.0  Engineering
1        Bob Jones  62000.0    Marketing
2    Charlie Brown      0.0      Finance
3     Diana Prince  75000.0          NaN
4      Evan Wright  92000.0  Engineering
5  Fiona Gallagher  58000.0           HR
6     George Clark      NaN    Marketing
7    Hannah Abbott      0.0      Finance
8      Ian Malcolm  81000.0        Sales
9    Julia Roberts  67000.0           HR
