In [1]:
import numpy as np

In [2]:
a= np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [3]:
a=np.array(["apple","banana","mango"])
print(a)

['apple' 'banana' 'mango']


In [4]:
a=np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [5]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
a=np.array([1,2,3])
print(a.ndim)

1


In [8]:
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


In [9]:
a=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print(a)
print(a.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]
3


In [10]:
a=np.array(([[[[1,2],[3,4]],[[5,6],[6,7]]],[[[1,2],[3,4]],[[5,6],[6,7]]]]))
print(a)
print(a.ndim)

[[[[1 2]
   [3 4]]

  [[5 6]
   [6 7]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [6 7]]]]
4


In [11]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [12]:
a=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print(a.shape)

(2, 2, 2)


In [13]:
a=np.array(([[[[1,2],[3,4]],[[5,6],[6,7]]],[[[1,2],[3,4]],[[5,6],[6,7]]]]))
print(a)
print(a.ndim)
print(a.shape)

[[[[1 2]
   [3 4]]

  [[5 6]
   [6 7]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [6 7]]]]
4
(2, 2, 2, 2)


In [14]:
a=np.array(([[[[[1,2],[3,4]],[[5,6],[6,7]]],[[[1,2],[3,4]],[[5,6],[6,7]]]],[[[[1,2],[3,4]],[[5,6],[6,7]]],[[[1,2],[3,4]],[[5,6],[6,7]]]],[[[[1,2],[3,4]],[[5,6],[6,7]]],[[[1,2],[3,4]],[[5,6],[6,7]]]],[[[[1,2],[3,4]],[[5,6],[6,7]]],[[[1,2],[3,4]],[[5,6],[6,7]]]]]))
print(a)
print(a.ndim)
print(a.shape)

[[[[[1 2]
    [3 4]]

   [[5 6]
    [6 7]]]


  [[[1 2]
    [3 4]]

   [[5 6]
    [6 7]]]]



 [[[[1 2]
    [3 4]]

   [[5 6]
    [6 7]]]


  [[[1 2]
    [3 4]]

   [[5 6]
    [6 7]]]]



 [[[[1 2]
    [3 4]]

   [[5 6]
    [6 7]]]


  [[[1 2]
    [3 4]]

   [[5 6]
    [6 7]]]]



 [[[[1 2]
    [3 4]]

   [[5 6]
    [6 7]]]


  [[[1 2]
    [3 4]]

   [[5 6]
    [6 7]]]]]
5
(4, 2, 2, 2, 2)


In [15]:
a=np.array([[1,2],[3,4]])
print(a.size)

4


In [16]:
a=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(type(a))
print(a[0,1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]
3
(2, 2, 2)
8
int32
<class 'numpy.ndarray'>
4


In [17]:
a=np.array([10,20,30,40])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[10 20 30 40]
1
(4,)
4
int32


In [18]:
a=np.array(([[[[1,2],[3,4]],[[5,6],[6,7]]],[[[1,2],[3,4]],[[5,6],[6,7]]]]))
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[[[[1 2]
   [3 4]]

  [[5 6]
   [6 7]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [6 7]]]]
4
(2, 2, 2, 2)
16
int32


In [19]:
import numpy as np
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
a=np.empty((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [24]:
a=np.empty((3,3))
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
a=np.empty((5,2))
print(a)

[[ 1.63783445e-307  4.24399158e-314]
 [-6.17056066e+303  1.27319425e-313]
 [ 9.83339641e-308  9.83366801e-308]
 [-3.04254794e+292  9.83366802e-308]
 [ 0.00000000e+000  0.00000000e+000]]


In [26]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [27]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [28]:
a=np.arange(1,21,5)
print(a)

[ 1  6 11 16]


In [29]:
a=np.arange(12)
print(a)
b=a.reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
a=np.array([[1,2],[3,4]])
print(a.flatten())

[1 2 3 4]


In [31]:
a=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print(a.flatten())

[1 2 3 4 5 6 6 7]


In [32]:
a=np.array([10,20,30,40])
print(a[-1])

40


In [33]:
a=np.array([10,20,30,40])
print(a[0])

10


In [34]:
a=np.array([10,20,30,40])
print(a[1])

20


In [35]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


In [36]:
import numpy as np
a=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(type(a))
print(a.flatten())
print(a.reshape(3,3))
print(a[0,0])
o=np.zeros((2,2))
print(o)
k=np.ones((2,2))
print(k)
print(np.eye(3))

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
3
(3, 1, 3)
9
int32
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
a=np.array([10,20,30,40])
print(a[1:4])

[20 30 40]


In [38]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a+b)

[11 22 33 44]


In [39]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a-b)

[ 9 18 27 36]


In [40]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a*b)

[ 1  4  9 16]


In [41]:
marks=np.array([1,2,3,4])
print(np.mean(marks))

2.5


In [42]:
a=np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [43]:
a=np.zeros([4,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
a=np.arange(1,11)
b=a.reshape(2,5)
print(b.shape)

(2, 5)


In [46]:
a=np.arange(1,13)
print(a)
b=a.reshape(3,4)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
a=np.arange(0,65)
print(np.max(a))
print(np.min(a))

64
0


In [48]:
a=np.array([12,10,13])
mean=np.mean(a)
print(mean)

11.666666666666666


In [49]:
a=np.array([12,10,13])
median=np.median(a)
print(median)

12.0


In [50]:
a=np.array([12,10,13])
std=np.std(a)
print(std)

1.247219128924647


In [51]:
a=np.array([1,2,4,6,21])
a.sort
print(a)

[ 1  2  4  6 21]


In [52]:
a=np.array([20,45,55,69,90,95])
print(a[a>50])

[55 69 90 95]


In [53]:
import random
for i in range(10): 
    print(random.randint(1,100))

32
99
40
66
42
48
53
10
97
11


In [54]:
i=0
while i<10:
    print(i)
    i=i+1

0
1
2
3
4
5
6
7
8
9


In [56]:
a=int(input("enter a number"))
b=int(input("enter another number"))
op=input("enter oprator:")
match(op):
    case "+":
        print("add",a+b)
    case "-":
        print("sub",a-b)
    case "*":
        print("product",a*b)
    case "/":
        print("divide",a/b)
    case "%":
        print("modulus",a%b)
        

enter a number 2
enter another number 3
enter oprator: *


product 6
